[package]
name = "hackernews_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = {version = "0.16.0", features = ["persistence"]}
firebase-rs = "1.0.3"
serde = { version = "1.0.136", features = ["derive"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.7"
